branches:
    only:
        - master

sudo: required
dist: trusty

services:
    - redis

language: python
python:
    - "2.7"
    - "3.4"

virtualenv:
    system_site_packages: true

before_install:
    - sudo add-apt-repository -y ppa:reddit/ppa
    - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
    - sudo apt-key add puppet/modules/cassandra/files/repo_key
    - sudo apt-get update -q
    - >
        sudo apt-get install -y \
            cassandra=2.2.8 \
            fbthrift-compiler \
            make \
            pylint \
            python \
            python3 \
            python3-cassandra \
            python3-coverage \
            python3-cqlmapper \
            python3-fbthrift \
            python3-gevent \
            python3-nose \
            python3-posix-ipc \
            python3-pymemcache \
            python3-redis \
            python3-requests \
            python3-setuptools \
            python3-sqlalchemy \
            python3-webtest \
            python-alabaster \
            python-coverage \
            python-cqlmapper \
            python-enum34 \
            python-fbthrift \
            python-flake8 \
            python-gevent \
            python-mock \
            python-nose \
            python-posix-ipc \
            python-pymemcache \
            python-pyramid \
            python-redis \
            python-requests \
            python-setuptools \
            python-sphinx \
            python-sphinxcontrib.spelling \
            python-sqlalchemy \
            python-webtest
    - sudo service cassandra start
    - sleep 10  # cassandra takes a while to start up

script:
    - make
    - nosetests -v
    - sphinx-build -M doctest docs/ build/
    - sphinx-build -M spelling docs/ build/
    - make lint
